### PR TITLE
Add sleep before executing esxcli to make sure ESXi login success and ready for CLI.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@turtle-fly @fub2 @XiaowenJiang @xiar @chenge3 @WinnieXU1

### CODE REVIEW

**Comment by turtle-fly** [comment]
@JuneZhou19 a little confused here:

I see a `send_command_wait_string` is called above, that function only returns when a prompt is detected, which means shell is already ready for next command.
How it comes that another 2 second is needed before `esx_test_ipmi_fru`?

**Comment by fub2** [comment]
Is that sleep really required? @JuneZhou19? any test failure reported because of esxi login failure without this delay?

**Comment by turtle-fly** [comment]
@JuneZhou19 please take a look at this PR~

**Comment by JuneZhou19** [comment]
Yes, it's required, since login need time. I run into connection issue, and after add sleep issue gone.

**Comment by JuneZhou19** [comment]
@fub2 @turtle-fly

**Comment by turtle-fly** [comment]
OK, and this change is included in PR#108, and get merged.
This PR could be closed.

**Comment by JuneZhou19** [comment]
This change is included in PR#108, and merged. So closing it.

**Pull request closed without merging**
