### PR TITLE
enhance logging for update config option to further root cause option update failure

### PR DESCRIPTION
**Pull request by JuneZhou19**
@InfraSIM/infrasim_dev

### CODE REVIEW

**Comment by JuneZhou19** [comment]
@InfraSIM/infrasim_dev Can any of you review the PR, it adds logs which helps to narrow down the CI Puffer test occasionally shows up:

130052 | block | Tried   ssh to guest on s2600wtt_192.168.133.177 for 30 times already, but still failed.

**Comment by JuneZhou19** [comment]
@chenc52 @fub2 @XiaowenJiang @xiar @turtle-fly  Can you pls help to review? It helps narrow down CI test issue in 130052 and 97939.

**Comment by JuneZhou19** [comment]
@chenc52 @fub2 @XiaowenJiang @xiar @turtle-fly Can you pls help to review? It helps narrow down CI test issue in 130052 and 97939.

**Comment by fub2** [comment]
@chenge3 can you review?

**Comment by chenge3** [comment]
👍

**Comment by JuneZhou19** [comment]
@turtle-fly Can you also pls have a review? Thanks!

**Comment by emcinfrasim** [comment]
@XiaowenJiang pls help review? Thanks！

**Comment by JuneZhou19** [comment]
@XiaowenJiang Can you pls review? Thanks!

**Pull request merged**
