### PR TITLE
feature/esxi_operation

### PR DESCRIPTION
**Pull request by turtle-fly**
CBaseCase.py
- Added hypervisor SSH config and deconfig
- Extract SSH config function for either BMC SSH or hypervisor SSH

Hypervisor.py
Added vim-cmd operation to:
- Get VM ID by VM name and datastore
- Power on/off VM by hypervisor SDK
- Delete/Add drive by hypervisor SDK
- Query image in datastore

SSH.py
- Enhance remote_shell to response until exit status ready, which
means data flow is all transferred.

### CODE REVIEW

**Comment by turtle-fly** [comment]
@sharkconi @xiar @PaynePei @JuneZhou19 @helloarys @fub2

**Comment by JuneZhou19** [comment]
With current implementation, it may always test one kind of node every time, right? Can we make sure to cover all nodes testing by testing a different node every day?

**Comment by turtle-fly** [comment]
@JuneZhou19 puffer can definitely pick up a type of node according to the date, do you have further requirement on the coverage matrix?

**Comment by JuneZhou19** [comment]
@turtle-fly sounds good, pls go ahead. No further comments on coverage.

**Comment by turtle-fly** [comment]
Hypervisor:
- Add operation to delete drive on certain scsi controller:unit

Stack:
- In mount disk operation, only delete scsi 0:1 disk instead of
all disks

T33248:
- Select random node to do test
- Umount ubuntu disk after test

Pass local test.

**Pull request merged**
