### PR TITLE
Update "requests" package import to latest version

### PR DESCRIPTION
**Pull request by XiaowenJiang**

### CODE REVIEW

**Comment by fub2** [comment]
@turtle-fly

**Comment by turtle-fly** [comment]
a PR in May - -!
@XiaowenJiang please help recall the reason to do this change.

I just have a test on python 2.7.12...

    infrasim@infrasim:~$ python
    Python 2.7.12 (default, Nov 19 2016, 06:48:10)
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from requests.packages import urllib3
    >>> from requests import urllib3
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name urllib3
    >>>

**Comment by turtle-fly** [comment]
@XiaowenJiang let's check the necessary package version of `requests` and make it in `requirements.txt`

**Comment by XiaowenJiang** [comment]
@turtle-fly seems the requests issue doesn't block the tests these days. I'll take a look

**Comment by fub2** [comment]
Close it if it no longer necessary.

**Comment by fub2** [comment]
When I was installing infrasim-compute, it kept complaining about:
```
installing OpenIpmi...
downloading Seabios...
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLCon
text object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connecti
ons to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readth
edocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLCon
text object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connecti
ons to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readth
edocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLCon
text object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connecti
ons to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readth
edocs.io/en/latest/security.html#insecureplatformwarning.
```
it is related to this urllib3?

**Comment by turtle-fly** [comment]
@fub2 what's your python version and urllib3 version?

    python --version
    pip show urllib3

@XiaowenJiang does above case recall the failure you met before?

**Comment by XiaowenJiang** [comment]
@fub2  I met these warning before when I tried to do infrasim init on a vm. I think it's related to SSL certificates. What machine were you using when the warning popped up?

**Pull request closed without merging**
