### PR TITLE
Extract docker container IP pool from docker log.

### PR DESCRIPTION
**Pull request by JuneZhou19**
The pr enables current utility scripts to analyze docker.log, which is generated while deploying docker InfraSIM, and get container IP pool so as to generate stack.json file for docker InfraSIM test scenario. 

After this, we can enable Jenkins to test InfraSIM docker builds with docker deployment script in place soon.

@xiar @weia5-emc @turtle-fly @chenc52 @XiaowenJiang @chenc52 @fub2

### CODE REVIEW

**Comment by JuneZhou19** [comment]
@xiar @weia5-emc @turtle-fly @chenc52 @XiaowenJiang @chenc52 @fub2 
Aaron's patch is in repo, so no dependency for the PR now. Pls review, thanks~

**Comment by fub2** [comment]
+1

**Comment by fub2** [comment]
@turtle-fly

**Comment by turtle-fly** [comment]
Clear!

**Pull request merged**
